// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://airpomlmvtfcetyvdmsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpcnBvbWxtdnRmY2V0eXZkbXNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzODkzODMsImV4cCI6MjA4NTk2NTM4M30.O5JP03qvUmMxE2YCog2-GRfBpXj5ln7YWD6x4Jvf0AY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});